"""
Run 1 - verified mature only.

No new analysis code. This invokes the parent folder's
Step_03_match_and_validate.py exactly as it stands, with one flag changed:

    --maturity "verified mature"

Everything else is Run 0: NVIS-constrained matching, Eq. (1) of the window-mean
FPI, all 174 predictors, PCA to 95% of the historical variance, the 99th
percentile no-analogue cutoff.

Why the parent folder needs protecting, and how
-----------------------------------------------
Step_03 names its outputs from the feature set, the constraint and the
averaging order - but NOT from the maturity classes. So running it with a
different `--maturity` writes over `matches_nvis.csv` and its companions, which
are the published Run 0 results.

The protection is a FILE-LEVEL backup, not a git one. An earlier version of
this script trusted `git status` and `git checkout` to put the parent back, and
that silently failed: `matches*.csv` is listed in the repository's .gitignore,
so git never reported it as modified and could not restore it. The Run 0 match
table was overwritten and had to be regenerated by re-running Step_03. Git can
only protect what git tracks, and half of what Step_03 writes it does not.

So this script:

    1. copies every file Step_03 will write into a private backup directory,
       recording which existed beforehand,
    2. runs Step_03 with the flag,
    3. copies the six results into Run_01/outputs/,
    4. puts the backup back, byte for byte, and deletes any file that Step_03
       created where none existed before,
    5. verifies each restored file matches its backup by size and content hash,
       and refuses to exit quietly if one does not.

Step 4 runs whether step 2 succeeded or failed. Nothing in
Space_time_validation/ is modified by a successful or an unsuccessful run.

The hypothesis under test
-------------------------
In the present-day gate the two maturity classes behave very differently, on
almost the same observed biomass:

    class             n     median M'/AGB   Spearman rho   observed AGB
    verified mature   327   0.613           0.492          117.5
    likely mature     273   0.338           0.389          109.8

and they differ sharply in a quantity that has nothing to do with M': biomass
per unit of the stand's own live basal area, 7.3 against 17.4 Mg per m2/ha. The
second figure is at the top of what a stand can physically carry, and it is the
signature of the small-plot inflation this library carries throughout - a
per-hectare figure from a small plot is a few large trees multiplied by a large
number. So the question is whether the likely-mature half, admitted on a
largest stem of 30-50 cm rather than a verified stem over 50 cm, was dragging
the headline numbers down.

Reads   ../../Step_03_match_and_validate.py            run unchanged
        ../../outputs/reference_table.csv, tables/*.npz
Writes  outputs/matches_nvis.csv                        and five companions
        outputs/step_03_console.log

Run
---
    conda run --no-capture-output -p "C:\\ProgramData\\Anaconda3\\envs\\JinzhuLuto" ^
        python Step_01_run_verified_only.py
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
STV = HERE.parents[1]                     # Space_time_validation/
SRC_OUT = STV / "outputs"
OUT_DIR = HERE / "outputs"
BACKUP = HERE / "_parent_backup"

STEP_03 = STV / "Step_03_match_and_validate.py"
SUFFIX = "_nvis"
PRODUCED = ["matches%s.csv", "metrics_by_run%s.csv", "metrics_by_maturity%s.csv",
            "no_analogue_summary%s.csv", "paired_log_ratio%s.csv",
            "matching_space%s.csv"]


def parent_files():
    return [SRC_OUT / (p % SUFFIX) for p in PRODUCED]


def digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def back_up():
    """Copy aside every file Step_03 is about to write.

    Returns {path: digest or None}, where None records a file that did not
    exist beforehand and must therefore be deleted on restore rather than
    replaced.
    """
    BACKUP.mkdir(parents=True, exist_ok=True)
    state = {}
    for p in parent_files():
        if p.exists():
            shutil.copy2(p, BACKUP / p.name)
            state[p] = digest(p)
        else:
            state[p] = None
    kept = sum(1 for v in state.values() if v is not None)
    print("backed up %d of %d parent files into %s"
          % (kept, len(state), BACKUP))
    return state


def restore(state):
    """Put the parent back exactly, and verify it."""
    problems = []
    for p, before in state.items():
        if before is None:
            if p.exists():
                p.unlink()
            continue
        src = BACKUP / p.name
        if not src.exists():
            problems.append("%s: backup missing" % p.name)
            continue
        shutil.copy2(src, p)
        if digest(p) != before:
            problems.append("%s: restored copy does not match the backup"
                            % p.name)
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--maturity", default="verified mature",
                    help="the one flag this run changes")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    cmd = [sys.executable, str(STEP_03), "--maturity", args.maturity]
    print("running the parent's Step_03 unchanged:")
    print("    %s --maturity %r\n" % (STEP_03.name, args.maturity))

    state = back_up()
    log = OUT_DIR / "step_03_console.log"
    try:
        r = subprocess.run(cmd, cwd=str(STV), capture_output=True, text=True)
        log.write_text((r.stdout or "") + (r.stderr or ""), encoding="utf-8")
        if r.stdout:
            print(r.stdout[-1500:])
        if r.returncode != 0:
            if r.stderr:
                print(r.stderr[-1500:])
            raise SystemExit("Step_03 failed - see %s" % log)

        copied = 0
        for p in parent_files():
            if p.exists():
                shutil.copy2(p, OUT_DIR / p.name)
                copied += 1
            else:
                print("  expected but not written: %s" % p.name)
        print("\ncopied %d result files into %s" % (copied, OUT_DIR))
    finally:
        problems = restore(state)
        if problems:
            print("\nWARNING - the parent was NOT fully restored:")
            for t in problems:
                print("   ", t)
            print("The backup is in %s - copy it back by hand." % BACKUP)
            raise SystemExit("Restore failed.")
        shutil.rmtree(BACKUP, ignore_errors=True)
        print("parent Run 0 outputs restored and verified by content hash - "
              "nothing there was changed")


if __name__ == "__main__":
    main()
